import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable";
import SidebarCollapsedOptions from "@/components/SidebarCollapsedOptions";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Sideabar } from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased min-h-screen`}>
        <SidebarProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Sideabar />
            <SidebarInset className="!h-svh p-2">
              <div className="bg-muted/60 relative h-full max-h-svh w-full rounded-xl p-4">
                <div className="absolute top-0 left-0 z-[50] flex h-12 w-full items-center justify-between px-3">
                  <SidebarCollapsedOptions />
                  <div className="flex items-center gap-2">
                    {/* <UpgradeCTA variant="topbar" />
                      <SelectTheme /> */}
                  </div>
                </div>
                <div className="mx-auto flex max-h-fit w-full max-w-3xl flex-col overflow-y-hidden">
                  <div className="flex-1">{children}</div>
                </div>
              </div>
            </SidebarInset>
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
